# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "collectd"
  s.version = "0.0.16"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stephan Maka"]
  s.date = "2012-01-26"
  s.email = "astro@spaceboyz.net"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rst"
  ]
  s.files = [
    "COPYING",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rst",
    "Rakefile",
    "VERSION.yml",
    "examples/em_sender.rb",
    "examples/sender.rb",
    "lib/collectd.rb",
    "lib/collectd/em_server.rb",
    "lib/collectd/em_support.rb",
    "lib/collectd/interface.rb",
    "lib/collectd/pkt.rb",
    "lib/collectd/proc_stats.rb",
    "lib/collectd/server.rb",
    "spec/interface_spec.rb"
  ]
  s.homepage = "http://github.com/astro/ruby-collectd"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Send collectd statistics from Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

